function init(selg)
	msg.post(".", "acquire_input_focus")

	self.button1 = gui.get_node("button")

	self.is_over1 = false

end

function on_input(self, action_id, action)
	--Start Game Input Code
	if(action_id == hash("click") and action.released == true) then
		local button = gui.get_node("button")
		if(gui.pick_node(button,action.x,action.y)) then
			print("click!!")
			msg.post("loader:/go#loader", "start_game")
			print("sent")
		end
	end
end